### ISSUE TITLE
Error Win7-64bit: jbstore fails (Error sizing blob)

### ISSUE THREAD

**Issue by thritter** [iSECPartners/jailbreak-Windows#1]
On Win7 (64Bit system):
Listing is fine:

> jbstore -l -s system
> Listing certificates in SYSTEM store
> Subject Name: IP Client
> Serial Number: 03 
> Subject Name: ....
> Serial Number: ....

But cannot export:

> jbstore -a -s system
> Error sizing blob: -2146893808
> jbstore -1 -s system
> Found the following certificate:
> Subject Name: IP Client
> Serial Number: 03 
> Error sizing blob: -2146893808

Any hint appreciated

**Comment by jcopenha** [comment]
Please see https://github.com/iSECPartners/jailbreak for a new version of jailbreak.
