### ISSUE TITLE
Hi! Pls fix it. Cause this utility not worked on win8 x64.

### ISSUE THREAD

**Issue by stcruzzo** [iSECPartners/jailbreak-Windows#2]
Microsoft Windows [Version 6.3.9600]

z:\distr\jailbreak-3.5>jbstore -1 -n "111@yak.net"
Found the following certificate:
Subject Name: 111@yak.net
Serial Number: 77 4d cc f3 00 02 00 00 37 9b

Error sizing blob: -2146893813
This is because jbstore2 is not working, please e-mail cclark or andreas.

z:\distr\jailbreak-3.5>

**Comment by ibernaus** [comment]
I'm facing with the same problem and the same OS version.
Any solution?

Thanks

**Comment by andreasjunestam** [comment]
This is fixed in version 4.0

**Comment by jcopenha** [comment]
Please see https://github.com/iSECPartners/jailbreak for a new version of jailbreak.
